version: "3.3"

services:

  cassandra-seed:
    image: cassandra:latest
    ports:
      - "9042:9042"
    volumes:
      - "cassandra_data_seed:/var/lib/cassandra"
    environment:
      - "CASSANDRA_SEEDS=cassandra-seed,cassandra_node1,cassandra_node2,cassandra_node3"
      - "CASSANDRA_CLUSTER_NAME=Test Cluster"
      - "CASSANDRA_DC=datacenter1"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
      - "CASSANDRA_USER=cassandra"
      - "CASSANDRA_PASSWORD=cassandra"
      - "MAX_HEAP_SIZE=500M"
      - "HEAP_NEWSIZE=200M"

  cassandra_node1:
    image: cassandra:latest
    volumes:
      - "cassandra_data_1:/var/lib/cassandra"
    environment:
      - "CASSANDRA_SEEDS=cassandra-seed,cassandra_node1,cassandra_node2,cassandra_node3"
      - "CASSANDRA_CLUSTER_NAME=Test Cluster"
      - "CASSANDRA_DC=datacenter1"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
      - "CASSANDRA_USER=cassandra"
      - "CASSANDRA_PASSWORD=cassandra"
      - "MAX_HEAP_SIZE=500M"
      - "HEAP_NEWSIZE=200M"
    depends_on:
      - cassandra-seed

  cassandra_node2:
    image: cassandra:latest
    volumes:
      - "cassandra_data_2:/var/lib/cassandra"
    environment:
      - "CASSANDRA_SEEDS=cassandra-seed,cassandra_node1,cassandra_node2,cassandra_node3"
      - "CASSANDRA_CLUSTER_NAME=Test Cluster"
      - "CASSANDRA_DC=datacenter1"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
      - "CASSANDRA_USER=cassandra"
      - "CASSANDRA_PASSWORD=cassandra"
      - "MAX_HEAP_SIZE=500M"
      - "HEAP_NEWSIZE=200M"
    depends_on:
      - cassandra-seed

  cassandra_node3:
    image: cassandra:latest
    volumes:
      - "cassandra_data_3:/var/lib/cassandra"
    environment:
      - "CASSANDRA_SEEDS=cassandra-seed,cassandra_node1,cassandra_node2,cassandra_node3"
      - "CASSANDRA_CLUSTER_NAME=Test Cluster"
      - "CASSANDRA_DC=datacenter1"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
      - "CASSANDRA_USER=cassandra"
      - "CASSANDRA_PASSWORD=cassandra"
      - "MAX_HEAP_SIZE=500M"
      - "HEAP_NEWSIZE=200M"
    depends_on:
      - cassandra-seed

volumes:
  cassandra_data_seed:
  cassandra_data_1:
  cassandra_data_2:
  cassandra_data_3: