version: '3.3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.0
    volumes:
      - $PWD/config/kibana.yml:/usr/share/kibana/kibana.yml
      - $PWD/build/logs:/var/log:ro
    ports:
      - "5601:5601"

  logstash:
    image: docker.elastic.co/logstash/logstash:7.13.0
    volumes:
      - $PWD/config/logstash-sample.conf:/usr/share/logstash/config/logstash-sample.conf
    ports:
      - "5044:5044"

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.13.0
    user: root
    volumes:
      - $PWD/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - $PWD/build/logs:/var/log:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers/:/var/lib/docker/containers/:ro
      - /var/log/audit/:/var/log/audit/
    command: ["--strict.perms=false"]
    restart: always
    depends_on:
      - kibana