spring:
  application:
    name: discovery
  zipkin:
    enabled: true
server:
  port: 6001
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:6001/eureka}