CREATE TABLE EVENT(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  EVENT_TYPE VARCHAR(32) NOT NULL,
  PLACE VARCHAR(32) NOT NULL,
  SPEAKER VARCHAR(32) NOT NULL,
  TITLE VARCHAR(32) NOT NULL,
  DATE_TIME TIMESTAMP NOT NULL
);