server:
  port: 7001
spring:
  h2:
    console:
      enabled: true
  data:
    jpa:
      hibernate:
        ddl-auto: none
  datasource:
    url: jdbc:h2:mem:testdb
kafka:
  bootstrap-servers: localhost:9092