version: '3'

services:
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=tasks
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
      - mongo
    ports:
      - "8888:8081"